spring.application.name=CashSpring

spring.datasource.url=jdbc:postgresql://localhost:5432/cashspring
spring.datasource.username=postgres
spring.datasource.password=Bonilla2005

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# Spring Security - Usuario por defecto
spring.security.user.name=admin
spring.security.user.password=admin123